CREATE OR REPLACE PACKAGE PCKG_TDY_LG_TDYHTRADERE IS
  TYPE t_list IS RECORD(
				REQ_ID TDYH_TRADE_RECORD.REQ_ID%TYPE,
				PLATFORM_NUM TDYH_TRADE_RECORD.PLATFORM_NUM%TYPE,
				STATUS_CONFIRM TDYH_TRADE_RECORD.STATUS_CONFIRM%TYPE,
				TYPE_TRADE TDYH_TRADE_RECORD.TYPE_TRADE%TYPE,
				STATUS_IO TDYH_TRADE_RECORD.STATUS_IO%TYPE,
				CUST_NO TDYH_TRADE_RECORD.CUST_NO%TYPE,
				TRANSACTIONACCOUNTID TDYH_TRADE_RECORD.TRANSACTIONACCOUNTID%TYPE,
				TANO TDYH_TRADE_RECORD.TANO%TYPE,
				BI_APPLICATIONAMT TDYH_TRADE_RECORD.BI_APPLICATIONAMT%TYPE,
				BI_MONEYACCOUNT TDYH_TRADE_RECORD.BI_MONEYACCOUNT%TYPE,
				BI_CHANNELID TDYH_TRADE_RECORD.BI_CHANNELID%TYPE,
				BI_BUYFLAG TDYH_TRADE_RECORD.BI_BUYFLAG%TYPE,
				BI_TRANSACTORNAME TDYH_TRADE_RECORD.BI_TRANSACTORNAME%TYPE,
				BI_TRANSACTORCERTTYPE TDYH_TRADE_RECORD.BI_TRANSACTORCERTTYPE%TYPE,
				BI_TRANSACTORCERTNO TDYH_TRADE_RECORD.BI_TRANSACTORCERTNO%TYPE,
				BR_TRANSACTIONDATE TDYH_TRADE_RECORD.BR_TRANSACTIONDATE%TYPE,
				BR_LIQDATE TDYH_TRADE_RECORD.BR_LIQDATE%TYPE,
				RI_APPLICATIONVOL TDYH_TRADE_RECORD.RI_APPLICATIONVOL%TYPE,
				RI_LARGEREDEMPTIONFLAG TDYH_TRADE_RECORD.RI_LARGEREDEMPTIONFLAG%TYPE,
				CR_RETURNCODE TDYH_TRADE_RECORD.CR_RETURNCODE%TYPE,
				CR_APPSHEETSERIALNO TDYH_TRADE_RECORD.CR_APPSHEETSERIALNO%TYPE,
				CR_TRANSACTIONCFMDATE TDYH_TRADE_RECORD.CR_TRANSACTIONCFMDATE%TYPE,
				CR_FUNDCODE TDYH_TRADE_RECORD.CR_FUNDCODE%TYPE,
				CR_BUSINESSCODE TDYH_TRADE_RECORD.CR_BUSINESSCODE%TYPE,
				CR_APPLICATIONVOL TDYH_TRADE_RECORD.CR_APPLICATIONVOL%TYPE,
				CR_TASERIALNO TDYH_TRADE_RECORD.CR_TASERIALNO%TYPE,
				CR_APPLICATIONAMOUNT TDYH_TRADE_RECORD.CR_APPLICATIONAMOUNT%TYPE,
				CR_TARGETFUNDCODE TDYH_TRADE_RECORD.CR_TARGETFUNDCODE%TYPE,
				CR_TAACCOUNTID TDYH_TRADE_RECORD.CR_TAACCOUNTID%TYPE,
				CR_ORIGINAPPLICATIONVOL TDYH_TRADE_RECORD.CR_ORIGINAPPLICATIONVOL%TYPE,
				CR_CONFIRMEDVOL TDYH_TRADE_RECORD.CR_CONFIRMEDVOL%TYPE,
				CR_CONFIRMEDAMOUNT TDYH_TRADE_RECORD.CR_CONFIRMEDAMOUNT%TYPE,
				CR_CHARGE TDYH_TRADE_RECORD.CR_CHARGE%TYPE,
				CR_NAV TDYH_TRADE_RECORD.CR_NAV%TYPE,
				CR_DEFDIVIDENDDMETHOD TDYH_TRADE_RECORD.CR_DEFDIVIDENDDMETHOD%TYPE,
				CR_RETURNMSG TDYH_TRADE_RECORD.CR_RETURNMSG%TYPE,
				CR_PAYCENTERID TDYH_TRADE_RECORD.CR_PAYCENTERID%TYPE,
				CR_CHANNELID TDYH_TRADE_RECORD.CR_CHANNELID%TYPE,
				CR_DEPOSITACCT TDYH_TRADE_RECORD.CR_DEPOSITACCT%TYPE,
				DATE_CREATE TDYH_TRADE_RECORD.DATE_CREATE%TYPE,
				DATE_MODIFY TDYH_TRADE_RECORD.DATE_MODIFY%TYPE,
				O_APPSHEETSERIALNO TDYH_TRADE_RECORD.O_APPSHEETSERIALNO%TYPE,
				RREMARK TDYH_TRADE_RECORD.RREMARK%TYPE    );

TYPE ref_t_list IS REF CURSOR RETURN t_list;

TYPE trade_li IS RECORD(
				CUST_NO VARCHAR2(20),
				BEGINDATE VARCHAR2(16),
				ENDDATE VARCHAR2(16)    );

TYPE ref_trade_li IS REF CURSOR RETURN trade_li;

TYPE REF_SETCUR IS REF CURSOR;

PROCEDURE PROC_TDY_BAK_TDYHTRADERE_QUERY(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                totalNum OUT VARCHAR2,
                o_item_list OUT ref_t_list);
                
PROCEDURE PROC_TDY_LG_TDYHTRADERE_DETAIL(
                i_REQ_ID   IN VARCHAR2,
                o_retCode OUT VARCHAR2,
				o_REQ_ID OUT VARCHAR2,
				o_PLATFORM_NUM OUT VARCHAR2,
				o_STATUS_CONFIRM OUT VARCHAR2,
				o_TYPE_TRADE OUT VARCHAR2,
				o_STATUS_IO OUT VARCHAR2,
				o_CUST_NO OUT VARCHAR2,
				o_TRANSACTIONACCOUNTID OUT VARCHAR2,
				o_TANO OUT VARCHAR2,
				o_BI_APPLICATIONAMT OUT VARCHAR2,
				o_BI_MONEYACCOUNT OUT VARCHAR2,
				o_BI_CHANNELID OUT VARCHAR2,
				o_BI_BUYFLAG OUT VARCHAR2,
				o_BI_TRANSACTORNAME OUT VARCHAR2,
				o_BI_TRANSACTORCERTTYPE OUT VARCHAR2,
				o_BI_TRANSACTORCERTNO OUT VARCHAR2,
				o_BR_TRANSACTIONDATE OUT VARCHAR2,
				o_BR_LIQDATE OUT VARCHAR2,
				o_RI_APPLICATIONVOL OUT VARCHAR2,
				o_RI_LARGEREDEMPTIONFLAG OUT VARCHAR2,
				o_CR_RETURNCODE OUT VARCHAR2,
				o_CR_APPSHEETSERIALNO OUT VARCHAR2,
				o_CR_TRANSACTIONCFMDATE OUT VARCHAR2,
				o_CR_FUNDCODE OUT VARCHAR2,
				o_CR_BUSINESSCODE OUT VARCHAR2,
				o_CR_APPLICATIONVOL OUT VARCHAR2,
				o_CR_TASERIALNO OUT VARCHAR2,
				o_CR_APPLICATIONAMOUNT OUT VARCHAR2,
				o_CR_TARGETFUNDCODE OUT VARCHAR2,
				o_CR_TAACCOUNTID OUT VARCHAR2,
				o_CR_ORIGINAPPLICATIONVOL OUT VARCHAR2,
				o_CR_CONFIRMEDVOL OUT VARCHAR2,
				o_CR_CONFIRMEDAMOUNT OUT VARCHAR2,
				o_CR_CHARGE OUT VARCHAR2,
				o_CR_NAV OUT VARCHAR2,
				o_CR_DEFDIVIDENDDMETHOD OUT VARCHAR2,
				o_CR_RETURNMSG OUT VARCHAR2,
				o_CR_PAYCENTERID OUT VARCHAR2,
				o_CR_CHANNELID OUT VARCHAR2,
				o_CR_DEPOSITACCT OUT VARCHAR2,
				o_DATE_CREATE OUT VARCHAR2,
				o_DATE_MODIFY OUT VARCHAR2,
				o_O_APPSHEETSERIALNO OUT VARCHAR2,
				o_RREMARK OUT VARCHAR2,
                o_errMsg OUT VARCHAR2);

PROCEDURE PROC_TDY_LG_TDYHTRADERE_ADD(
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode     OUT VARCHAR2);
PROCEDURE PROC_TDY_LG_TDYHTRADERE_UPDATE(
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                          o_retCode OUT VARCHAR2) ;   
PROCEDURE PROC_TDY_LG_TDYHTRADERE_DEL(
                i_REQ_ID       IN  VARCHAR2,
                o_retCode     OUT VARCHAR2); 
                
PROCEDURE PROC_TDY_LG_SYNCLI(
                o_retCode     OUT VARCHAR2,
                o_trade_list OUT ref_trade_li);
                
PROCEDURE PROC_TDY_LG_SYNCTRADE_U(
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
                o_retCode OUT VARCHAR2);
                
PROCEDURE PROC_TDY_LG_TDYHTRADERE_QUERY(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                totalNum OUT VARCHAR2,
                o_item_list OUT REF_SETCUR);
--统计信息
  PROCEDURE PROC_TDY_LG_STATISTICS(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                --totalNum OUT VARCHAR2,
                o_item_list OUT REF_SETCUR);                
END;
/
CREATE OR REPLACE PACKAGE BODY PCKG_TDY_LG_TDYHTRADERE IS
 /******************************************************************************
   --       PROC_TDY_LG_TDYHTRADERE_QUERY
   -- 		查询数据
   -- 		输入参数：
   -- 			begNum    查询开始输入参数
   -- 			fetchNum  每次查询获取多少条数
   -- 		输出参数
   --   		o_retCode    返回标志位
   --   		totalNum     返回总条数
   --   		o_item_list  返回数据列表
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/
PROCEDURE PROC_TDY_BAK_TDYHTRADERE_QUERY(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                totalNum OUT VARCHAR2,
                o_item_list OUT ref_t_list) IS
BEGIN
   o_retCode:=0;
   SELECT count(*) INTO totalNum FROM TDYH_TRADE_RECORD a 
   	WHERE
 (i_REQ_ID IS NULL OR   a.REQ_ID =  i_REQ_ID
)
and  (i_PLATFORM_NUM IS NULL OR   a.PLATFORM_NUM =  i_PLATFORM_NUM
)
and  (i_STATUS_CONFIRM IS NULL OR   a.STATUS_CONFIRM =  i_STATUS_CONFIRM
)
and  (i_TYPE_TRADE IS NULL OR   a.TYPE_TRADE =  i_TYPE_TRADE
)
and  (i_STATUS_IO IS NULL OR   a.STATUS_IO =  i_STATUS_IO
)
and  (i_CUST_NO IS NULL OR   a.CUST_NO =  i_CUST_NO
)
and  (i_TRANSACTIONACCOUNTID IS NULL OR   a.TRANSACTIONACCOUNTID =  i_TRANSACTIONACCOUNTID
)
and  (i_TANO IS NULL OR   a.TANO =  i_TANO
)
and  (i_BI_APPLICATIONAMT IS NULL OR    a.BI_APPLICATIONAMT = TO_NUMBER(i_BI_APPLICATIONAMT)
)
and  (i_BI_MONEYACCOUNT IS NULL OR   a.BI_MONEYACCOUNT =  i_BI_MONEYACCOUNT
)
and  (i_BI_CHANNELID IS NULL OR   a.BI_CHANNELID =  i_BI_CHANNELID
)
and  (i_BI_BUYFLAG IS NULL OR   a.BI_BUYFLAG =  i_BI_BUYFLAG
)
and  (i_BI_TRANSACTORNAME IS NULL OR   a.BI_TRANSACTORNAME =  i_BI_TRANSACTORNAME
)
and  (i_BI_TRANSACTORCERTTYPE IS NULL OR   a.BI_TRANSACTORCERTTYPE =  i_BI_TRANSACTORCERTTYPE
)
and  (i_BI_TRANSACTORCERTNO IS NULL OR   a.BI_TRANSACTORCERTNO =  i_BI_TRANSACTORCERTNO
)
and  (i_BR_TRANSACTIONDATE IS NULL OR   a.BR_TRANSACTIONDATE =  i_BR_TRANSACTIONDATE
)
and  (i_BR_LIQDATE IS NULL OR   a.BR_LIQDATE =  i_BR_LIQDATE
)
and  (i_RI_APPLICATIONVOL IS NULL OR    a.RI_APPLICATIONVOL = TO_NUMBER(i_RI_APPLICATIONVOL)
)
and  (i_RI_LARGEREDEMPTIONFLAG IS NULL OR   a.RI_LARGEREDEMPTIONFLAG =  i_RI_LARGEREDEMPTIONFLAG
)
and  (i_CR_RETURNCODE IS NULL OR   a.CR_RETURNCODE =  i_CR_RETURNCODE
)
and  (i_CR_APPSHEETSERIALNO IS NULL OR   a.CR_APPSHEETSERIALNO =  i_CR_APPSHEETSERIALNO
)
and  (i_CR_TRANSACTIONCFMDATE IS NULL OR   a.CR_TRANSACTIONCFMDATE =  i_CR_TRANSACTIONCFMDATE
)
and  (i_CR_FUNDCODE IS NULL OR   a.CR_FUNDCODE =  i_CR_FUNDCODE
)
and  (i_CR_BUSINESSCODE IS NULL OR   a.CR_BUSINESSCODE =  i_CR_BUSINESSCODE
)
and  (i_CR_APPLICATIONVOL IS NULL OR    a.CR_APPLICATIONVOL = TO_NUMBER(i_CR_APPLICATIONVOL)
)
and  (i_CR_TASERIALNO IS NULL OR   a.CR_TASERIALNO =  i_CR_TASERIALNO
)
and  (i_CR_APPLICATIONAMOUNT IS NULL OR   a.CR_APPLICATIONAMOUNT =  i_CR_APPLICATIONAMOUNT
)
and  (i_CR_TARGETFUNDCODE IS NULL OR   a.CR_TARGETFUNDCODE =  i_CR_TARGETFUNDCODE
)
and  (i_CR_TAACCOUNTID IS NULL OR   a.CR_TAACCOUNTID =  i_CR_TAACCOUNTID
)
and  (i_CR_ORIGINAPPLICATIONVOL IS NULL OR   a.CR_ORIGINAPPLICATIONVOL =  i_CR_ORIGINAPPLICATIONVOL
)
and  (i_CR_CONFIRMEDVOL IS NULL OR    a.CR_CONFIRMEDVOL = TO_NUMBER(i_CR_CONFIRMEDVOL)
)
and  (i_CR_CONFIRMEDAMOUNT IS NULL OR    a.CR_CONFIRMEDAMOUNT = TO_NUMBER(i_CR_CONFIRMEDAMOUNT)
)
and  (i_CR_CHARGE IS NULL OR    a.CR_CHARGE = TO_NUMBER(i_CR_CHARGE)
)
and  (i_CR_NAV IS NULL OR    a.CR_NAV = TO_NUMBER(i_CR_NAV)
)
and  (i_CR_DEFDIVIDENDDMETHOD IS NULL OR   a.CR_DEFDIVIDENDDMETHOD =  i_CR_DEFDIVIDENDDMETHOD
)
and  (i_CR_RETURNMSG IS NULL OR   a.CR_RETURNMSG =  i_CR_RETURNMSG
)
and  (i_CR_PAYCENTERID IS NULL OR   a.CR_PAYCENTERID =  i_CR_PAYCENTERID
)
and  (i_CR_CHANNELID IS NULL OR   a.CR_CHANNELID =  i_CR_CHANNELID
)
and  (i_CR_DEPOSITACCT IS NULL OR   a.CR_DEPOSITACCT =  i_CR_DEPOSITACCT
)
and  (i_DATE_CREATE IS NULL OR   a.DATE_CREATE=TO_DATE(i_DATE_CREATE, 'yyyy-MM-dd')
)
and  (i_DATE_MODIFY IS NULL OR   a.DATE_MODIFY=TO_DATE(i_DATE_MODIFY, 'yyyy-MM-dd')
)
and  (i_O_APPSHEETSERIALNO IS NULL OR   a.O_APPSHEETSERIALNO =  i_O_APPSHEETSERIALNO
)
and  (i_RREMARK IS NULL OR   a.RREMARK =  i_RREMARK
)
;
   OPEN o_item_list FOR
   SELECT 
		REQ_ID,
		PLATFORM_NUM,
		STATUS_CONFIRM,
		TYPE_TRADE,
		STATUS_IO,
		CUST_NO,
		TRANSACTIONACCOUNTID,
		TANO,
		BI_APPLICATIONAMT,
		BI_MONEYACCOUNT,
		BI_CHANNELID,
		BI_BUYFLAG,
		BI_TRANSACTORNAME,
		BI_TRANSACTORCERTTYPE,
		BI_TRANSACTORCERTNO,
		BR_TRANSACTIONDATE,
		BR_LIQDATE,
		RI_APPLICATIONVOL,
		RI_LARGEREDEMPTIONFLAG,
		CR_RETURNCODE,
		CR_APPSHEETSERIALNO,
		CR_TRANSACTIONCFMDATE,
		CR_FUNDCODE,
		CR_BUSINESSCODE,
		CR_APPLICATIONVOL,
		CR_TASERIALNO,
		CR_APPLICATIONAMOUNT,
		CR_TARGETFUNDCODE,
		CR_TAACCOUNTID,
		CR_ORIGINAPPLICATIONVOL,
		CR_CONFIRMEDVOL,
		CR_CONFIRMEDAMOUNT,
		CR_CHARGE,
		CR_NAV,
		CR_DEFDIVIDENDDMETHOD,
		CR_RETURNMSG,
		CR_PAYCENTERID,
		CR_CHANNELID,
		CR_DEPOSITACCT,
		DATE_CREATE,
		DATE_MODIFY,
		O_APPSHEETSERIALNO,
		RREMARK
   FROM(SELECT 
		REQ_ID,
		PLATFORM_NUM,
		STATUS_CONFIRM,
		TYPE_TRADE,
		STATUS_IO,
		CUST_NO,
		TRANSACTIONACCOUNTID,
		TANO,
		BI_APPLICATIONAMT,
		BI_MONEYACCOUNT,
		BI_CHANNELID,
		BI_BUYFLAG,
		BI_TRANSACTORNAME,
		BI_TRANSACTORCERTTYPE,
		BI_TRANSACTORCERTNO,
		BR_TRANSACTIONDATE,
		BR_LIQDATE,
		RI_APPLICATIONVOL,
		RI_LARGEREDEMPTIONFLAG,
		CR_RETURNCODE,
		CR_APPSHEETSERIALNO,
		CR_TRANSACTIONCFMDATE,
		CR_FUNDCODE,
		CR_BUSINESSCODE,
		CR_APPLICATIONVOL,
		CR_TASERIALNO,
		CR_APPLICATIONAMOUNT,
		CR_TARGETFUNDCODE,
		CR_TAACCOUNTID,
		CR_ORIGINAPPLICATIONVOL,
		CR_CONFIRMEDVOL,
		CR_CONFIRMEDAMOUNT,
		CR_CHARGE,
		CR_NAV,
		CR_DEFDIVIDENDDMETHOD,
		CR_RETURNMSG,
		CR_PAYCENTERID,
		CR_CHANNELID,
		CR_DEPOSITACCT,
		DATE_CREATE,
		DATE_MODIFY,
		O_APPSHEETSERIALNO,
		RREMARK,
	ROWNUM           ROW_ID
	FROM TDYH_TRADE_RECORD a
	WHERE
 (i_REQ_ID IS NULL OR    a.REQ_ID =  i_REQ_ID
)
and  (i_PLATFORM_NUM IS NULL OR    a.PLATFORM_NUM =  i_PLATFORM_NUM
)
and  (i_STATUS_CONFIRM IS NULL OR    a.STATUS_CONFIRM =  i_STATUS_CONFIRM
)
and  (i_TYPE_TRADE IS NULL OR    a.TYPE_TRADE =  i_TYPE_TRADE
)
and  (i_STATUS_IO IS NULL OR    a.STATUS_IO =  i_STATUS_IO
)
and  (i_CUST_NO IS NULL OR    a.CUST_NO =  i_CUST_NO
)
and  (i_TRANSACTIONACCOUNTID IS NULL OR    a.TRANSACTIONACCOUNTID =  i_TRANSACTIONACCOUNTID
)
and  (i_TANO IS NULL OR    a.TANO =  i_TANO
)
and  (i_BI_APPLICATIONAMT IS NULL OR     a.BI_APPLICATIONAMT = TO_NUMBER(i_BI_APPLICATIONAMT)
)
and  (i_BI_MONEYACCOUNT IS NULL OR    a.BI_MONEYACCOUNT =  i_BI_MONEYACCOUNT
)
and  (i_BI_CHANNELID IS NULL OR    a.BI_CHANNELID =  i_BI_CHANNELID
)
and  (i_BI_BUYFLAG IS NULL OR    a.BI_BUYFLAG =  i_BI_BUYFLAG
)
and  (i_BI_TRANSACTORNAME IS NULL OR    a.BI_TRANSACTORNAME =  i_BI_TRANSACTORNAME
)
and  (i_BI_TRANSACTORCERTTYPE IS NULL OR    a.BI_TRANSACTORCERTTYPE =  i_BI_TRANSACTORCERTTYPE
)
and  (i_BI_TRANSACTORCERTNO IS NULL OR    a.BI_TRANSACTORCERTNO =  i_BI_TRANSACTORCERTNO
)
and  (i_BR_TRANSACTIONDATE IS NULL OR    a.BR_TRANSACTIONDATE =  i_BR_TRANSACTIONDATE
)
and  (i_BR_LIQDATE IS NULL OR    a.BR_LIQDATE =  i_BR_LIQDATE
)
and  (i_RI_APPLICATIONVOL IS NULL OR     a.RI_APPLICATIONVOL = TO_NUMBER(i_RI_APPLICATIONVOL)
)
and  (i_RI_LARGEREDEMPTIONFLAG IS NULL OR    a.RI_LARGEREDEMPTIONFLAG =  i_RI_LARGEREDEMPTIONFLAG
)
and  (i_CR_RETURNCODE IS NULL OR    a.CR_RETURNCODE =  i_CR_RETURNCODE
)
and  (i_CR_APPSHEETSERIALNO IS NULL OR    a.CR_APPSHEETSERIALNO =  i_CR_APPSHEETSERIALNO
)
and  (i_CR_TRANSACTIONCFMDATE IS NULL OR    a.CR_TRANSACTIONCFMDATE =  i_CR_TRANSACTIONCFMDATE
)
and  (i_CR_FUNDCODE IS NULL OR    a.CR_FUNDCODE =  i_CR_FUNDCODE
)
and  (i_CR_BUSINESSCODE IS NULL OR    a.CR_BUSINESSCODE =  i_CR_BUSINESSCODE
)
and  (i_CR_APPLICATIONVOL IS NULL OR     a.CR_APPLICATIONVOL = TO_NUMBER(i_CR_APPLICATIONVOL)
)
and  (i_CR_TASERIALNO IS NULL OR    a.CR_TASERIALNO =  i_CR_TASERIALNO
)
and  (i_CR_APPLICATIONAMOUNT IS NULL OR    a.CR_APPLICATIONAMOUNT =  i_CR_APPLICATIONAMOUNT
)
and  (i_CR_TARGETFUNDCODE IS NULL OR    a.CR_TARGETFUNDCODE =  i_CR_TARGETFUNDCODE
)
and  (i_CR_TAACCOUNTID IS NULL OR    a.CR_TAACCOUNTID =  i_CR_TAACCOUNTID
)
and  (i_CR_ORIGINAPPLICATIONVOL IS NULL OR    a.CR_ORIGINAPPLICATIONVOL =  i_CR_ORIGINAPPLICATIONVOL
)
and  (i_CR_CONFIRMEDVOL IS NULL OR     a.CR_CONFIRMEDVOL = TO_NUMBER(i_CR_CONFIRMEDVOL)
)
and  (i_CR_CONFIRMEDAMOUNT IS NULL OR     a.CR_CONFIRMEDAMOUNT = TO_NUMBER(i_CR_CONFIRMEDAMOUNT)
)
and  (i_CR_CHARGE IS NULL OR     a.CR_CHARGE = TO_NUMBER(i_CR_CHARGE)
)
and  (i_CR_NAV IS NULL OR     a.CR_NAV = TO_NUMBER(i_CR_NAV)
)
and  (i_CR_DEFDIVIDENDDMETHOD IS NULL OR    a.CR_DEFDIVIDENDDMETHOD =  i_CR_DEFDIVIDENDDMETHOD
)
and  (i_CR_RETURNMSG IS NULL OR    a.CR_RETURNMSG =  i_CR_RETURNMSG
)
and  (i_CR_PAYCENTERID IS NULL OR    a.CR_PAYCENTERID =  i_CR_PAYCENTERID
)
and  (i_CR_CHANNELID IS NULL OR    a.CR_CHANNELID =  i_CR_CHANNELID
)
and  (i_CR_DEPOSITACCT IS NULL OR    a.CR_DEPOSITACCT =  i_CR_DEPOSITACCT
)
and  (i_DATE_CREATE IS NULL OR    a.DATE_CREATE=TO_DATE(i_DATE_CREATE, 'yyyy-MM-dd')
)
and  (i_DATE_MODIFY IS NULL OR    a.DATE_MODIFY=TO_DATE(i_DATE_MODIFY, 'yyyy-MM-dd')
)
and  (i_O_APPSHEETSERIALNO IS NULL OR    a.O_APPSHEETSERIALNO =  i_O_APPSHEETSERIALNO
)
and  (i_RREMARK IS NULL OR    a.RREMARK =  i_RREMARK
)
)
    WHERE ROW_ID >= to_number(begNum) AND ROW_ID < to_number(begNum) + to_number(fetchNum);
    RETURN;
     EXCEPTION
    WHEN OTHERS THEN
      IF o_item_list%ISOPEN THEN
        CLOSE o_item_list;
      END IF;
      
      o_retCode := -1;
      RETURN;
  END;
  
   /******************************************************************************
   --       PROC_TDY_LG_TDYHTRADERE_DETAIL
   -- 		查询数据
   -- 		输入参数：
   -- 			REQ_ID    查询主键
   -- 		输出参数
   --   		o_retCode    返回标志位
   --   		o_errMsg  返回数据列表
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/
  PROCEDURE PROC_TDY_LG_TDYHTRADERE_DETAIL(
                i_REQ_ID   IN VARCHAR2,
                o_retCode OUT VARCHAR2,
				o_REQ_ID OUT VARCHAR2,
				o_PLATFORM_NUM OUT VARCHAR2,
				o_STATUS_CONFIRM OUT VARCHAR2,
				o_TYPE_TRADE OUT VARCHAR2,
				o_STATUS_IO OUT VARCHAR2,
				o_CUST_NO OUT VARCHAR2,
				o_TRANSACTIONACCOUNTID OUT VARCHAR2,
				o_TANO OUT VARCHAR2,
				o_BI_APPLICATIONAMT OUT VARCHAR2,
				o_BI_MONEYACCOUNT OUT VARCHAR2,
				o_BI_CHANNELID OUT VARCHAR2,
				o_BI_BUYFLAG OUT VARCHAR2,
				o_BI_TRANSACTORNAME OUT VARCHAR2,
				o_BI_TRANSACTORCERTTYPE OUT VARCHAR2,
				o_BI_TRANSACTORCERTNO OUT VARCHAR2,
				o_BR_TRANSACTIONDATE OUT VARCHAR2,
				o_BR_LIQDATE OUT VARCHAR2,
				o_RI_APPLICATIONVOL OUT VARCHAR2,
				o_RI_LARGEREDEMPTIONFLAG OUT VARCHAR2,
				o_CR_RETURNCODE OUT VARCHAR2,
				o_CR_APPSHEETSERIALNO OUT VARCHAR2,
				o_CR_TRANSACTIONCFMDATE OUT VARCHAR2,
				o_CR_FUNDCODE OUT VARCHAR2,
				o_CR_BUSINESSCODE OUT VARCHAR2,
				o_CR_APPLICATIONVOL OUT VARCHAR2,
				o_CR_TASERIALNO OUT VARCHAR2,
				o_CR_APPLICATIONAMOUNT OUT VARCHAR2,
				o_CR_TARGETFUNDCODE OUT VARCHAR2,
				o_CR_TAACCOUNTID OUT VARCHAR2,
				o_CR_ORIGINAPPLICATIONVOL OUT VARCHAR2,
				o_CR_CONFIRMEDVOL OUT VARCHAR2,
				o_CR_CONFIRMEDAMOUNT OUT VARCHAR2,
				o_CR_CHARGE OUT VARCHAR2,
				o_CR_NAV OUT VARCHAR2,
				o_CR_DEFDIVIDENDDMETHOD OUT VARCHAR2,
				o_CR_RETURNMSG OUT VARCHAR2,
				o_CR_PAYCENTERID OUT VARCHAR2,
				o_CR_CHANNELID OUT VARCHAR2,
				o_CR_DEPOSITACCT OUT VARCHAR2,
				o_DATE_CREATE OUT VARCHAR2,
				o_DATE_MODIFY OUT VARCHAR2,
				o_O_APPSHEETSERIALNO OUT VARCHAR2,
				o_RREMARK OUT VARCHAR2,
                o_errMsg OUT VARCHAR2) IS
BEGIN
   o_retCode:=0;
   o_errMsg:='';
   SELECT 
			REQ_ID,
			PLATFORM_NUM,
			STATUS_CONFIRM,
			TYPE_TRADE,
			STATUS_IO,
			CUST_NO,
			TRANSACTIONACCOUNTID,
			TANO,
			BI_APPLICATIONAMT,
			BI_MONEYACCOUNT,
			BI_CHANNELID,
			BI_BUYFLAG,
			BI_TRANSACTORNAME,
			BI_TRANSACTORCERTTYPE,
			BI_TRANSACTORCERTNO,
			BR_TRANSACTIONDATE,
			BR_LIQDATE,
			RI_APPLICATIONVOL,
			RI_LARGEREDEMPTIONFLAG,
			CR_RETURNCODE,
			CR_APPSHEETSERIALNO,
			CR_TRANSACTIONCFMDATE,
			CR_FUNDCODE,
			CR_BUSINESSCODE,
			CR_APPLICATIONVOL,
			CR_TASERIALNO,
			CR_APPLICATIONAMOUNT,
			CR_TARGETFUNDCODE,
			CR_TAACCOUNTID,
			CR_ORIGINAPPLICATIONVOL,
			CR_CONFIRMEDVOL,
			CR_CONFIRMEDAMOUNT,
			CR_CHARGE,
			CR_NAV,
			CR_DEFDIVIDENDDMETHOD,
			CR_RETURNMSG,
			CR_PAYCENTERID,
			CR_CHANNELID,
			CR_DEPOSITACCT,
			TO_CHAR(DATE_CREATE,'yyyy-MM-dd'),
			TO_CHAR(DATE_MODIFY,'yyyy-MM-dd'),
			O_APPSHEETSERIALNO,
			RREMARK
	INTO
			o_REQ_ID,
			o_PLATFORM_NUM,
			o_STATUS_CONFIRM,
			o_TYPE_TRADE,
			o_STATUS_IO,
			o_CUST_NO,
			o_TRANSACTIONACCOUNTID,
			o_TANO,
			o_BI_APPLICATIONAMT,
			o_BI_MONEYACCOUNT,
			o_BI_CHANNELID,
			o_BI_BUYFLAG,
			o_BI_TRANSACTORNAME,
			o_BI_TRANSACTORCERTTYPE,
			o_BI_TRANSACTORCERTNO,
			o_BR_TRANSACTIONDATE,
			o_BR_LIQDATE,
			o_RI_APPLICATIONVOL,
			o_RI_LARGEREDEMPTIONFLAG,
			o_CR_RETURNCODE,
			o_CR_APPSHEETSERIALNO,
			o_CR_TRANSACTIONCFMDATE,
			o_CR_FUNDCODE,
			o_CR_BUSINESSCODE,
			o_CR_APPLICATIONVOL,
			o_CR_TASERIALNO,
			o_CR_APPLICATIONAMOUNT,
			o_CR_TARGETFUNDCODE,
			o_CR_TAACCOUNTID,
			o_CR_ORIGINAPPLICATIONVOL,
			o_CR_CONFIRMEDVOL,
			o_CR_CONFIRMEDAMOUNT,
			o_CR_CHARGE,
			o_CR_NAV,
			o_CR_DEFDIVIDENDDMETHOD,
			o_CR_RETURNMSG,
			o_CR_PAYCENTERID,
			o_CR_CHANNELID,
			o_CR_DEPOSITACCT,
			o_DATE_CREATE,
			o_DATE_MODIFY,
			o_O_APPSHEETSERIALNO,
			o_RREMARK
   FROM  TDYH_TRADE_RECORD
   WHERE REQ_ID=i_REQ_ID;
    RETURN;
   EXCEPTION
    WHEN OTHERS THEN
      o_errMsg := SUBSTR( SQLCODE || ':' || SQLERRM ||
                     DBMS_UTILITY.FORMAT_ERROR_BACKTRACE(),
                     1, 800 );
      o_retCode := -1;
    RETURN;
  END;
  
 /******************************************************************************
   --       PROC_TDY_LG_TDYHTRADERE_UPDATE
   -- 		更新数据
   -- 		输入参数：
   --	i_REQ_ID  i_本地生成的任务id
   --	i_PLATFORM_NUM  i_客户平台编号
   --	i_STATUS_CONFIRM  i_交易确认状态 0未确认 1已确认 2已成功撤单 3废单（若想知道是废单需调用客户交易记录接口，暂时无此动作）
   --	i_TYPE_TRADE  i_调用接口 01:PURCHASE-520003-手机基金认申购 02:CANCEL_ORDER-520006-用户交易撤单 03:REDEEM-520004-用户份额赎回
   --	i_STATUS_IO  i_0:支出交易 1:收入交易 2:取消交易
   --	i_CUST_NO  i_客户号
   --	i_TRANSACTIONACCOUNTID  i_交易账户
   --	i_TANO  i_TA代码
   --	i_BI_APPLICATIONAMT  i_申请金额(BI_...为购买接口入参)
   --	i_BI_MONEYACCOUNT  i_资金账户
   --	i_BI_CHANNELID  i_支付网点[110080]
   --	i_BI_BUYFLAG  i_强制购买标志，'0' 非强制购买，'1' 强制购买
   --	i_BI_TRANSACTORNAME  i_监护人姓名未成年人交易必填
   --	i_BI_TRANSACTORCERTTYPE  i_账户经办人证件类型 未成年人交易必填[110047]
   --	i_BI_TRANSACTORCERTNO  i_监护人证件号码未成年人交易必填
   --	i_BR_TRANSACTIONDATE  i_交易发生日期 格式为：YYYYMMDD
   --	i_BR_LIQDATE  i_购买结算日期 格式为：YYYYMMDD
   --	i_RI_APPLICATIONVOL  i_申请份数(RI_...为赎回接口返回入参)
   --	i_RI_LARGEREDEMPTIONFLAG  i_巨额赎回标志，0-放弃超额部分1-继续赎回，预约赎回、转换 
   --	i_CR_RETURNCODE  i_(CR_...为查询交易确认返回的数据)
   --	i_CR_APPSHEETSERIALNO  i_申请单编号
   --	i_CR_TRANSACTIONCFMDATE  i_crTransactioncfmdate
   --	i_CR_FUNDCODE  i_基金代码
   --	i_CR_BUSINESSCODE  i_业务类型[130010]
   --	i_CR_APPLICATIONVOL  i_申请基金份数 初始申报
   --	i_CR_TASERIALNO  i_TA 确认流水号
   --	i_CR_APPLICATIONAMOUNT  i_申请金额
   --	i_CR_TARGETFUNDCODE  i_目标基金代码
   --	i_CR_TAACCOUNTID  i_基金帐号
   --	i_CR_ORIGINAPPLICATIONVOL  i_原申请单编号 027 业务使用，表示转出时的申请单编号
   --	i_CR_CONFIRMEDVOL  i_确认份额
   --	i_CR_CONFIRMEDAMOUNT  i_确认金额
   --	i_CR_CHARGE  i_手续费
   --	i_CR_NAV  i_当日基金净值
   --	i_CR_DEFDIVIDENDDMETHOD  i_分红方式‘0’-红利转投‘1’-现金分红[110001]
   --	i_CR_RETURNMSG  i_交易处理返回代码系统处理后返回错误信息
   --	i_CR_PAYCENTERID  i_支付网点所属中心，查看数据字典[110079]
   --	i_CR_CHANNELID  i_支付渠道代码，查看数据字典[110080]
   --	i_CR_DEPOSITACCT  i_投资人银行卡号
   --	i_DATE_CREATE  i_记录创建日期
   --	i_DATE_MODIFY  i_记录最后修改日期
   --	i_O_APPSHEETSERIALNO  i_请求接口时返回的原始单号，备份对比用
   --	i_RREMARK  i_预留

   -- 		输出参数
   --   		o_retCode    返回标志位
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/
PROCEDURE PROC_TDY_LG_TDYHTRADERE_UPDATE(
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2) IS
BEGIN
   o_retCode:='0';
       UPDATE TDYH_TRADE_RECORD
       SET
            REQ_ID =  i_REQ_ID,
            PLATFORM_NUM =  i_PLATFORM_NUM,
            STATUS_CONFIRM =  i_STATUS_CONFIRM,
            TYPE_TRADE =  i_TYPE_TRADE,
            STATUS_IO =  i_STATUS_IO,
            CUST_NO =  i_CUST_NO,
            TRANSACTIONACCOUNTID =  i_TRANSACTIONACCOUNTID,
            TANO =  i_TANO,
            BI_APPLICATIONAMT = TO_NUMBER(i_BI_APPLICATIONAMT),
            BI_MONEYACCOUNT =  i_BI_MONEYACCOUNT,
            BI_CHANNELID =  i_BI_CHANNELID,
            BI_BUYFLAG =  i_BI_BUYFLAG,
            BI_TRANSACTORNAME =  i_BI_TRANSACTORNAME,
            BI_TRANSACTORCERTTYPE =  i_BI_TRANSACTORCERTTYPE,
            BI_TRANSACTORCERTNO =  i_BI_TRANSACTORCERTNO,
            BR_TRANSACTIONDATE =  i_BR_TRANSACTIONDATE,
            BR_LIQDATE =  i_BR_LIQDATE,
            RI_APPLICATIONVOL = TO_NUMBER(i_RI_APPLICATIONVOL),
            RI_LARGEREDEMPTIONFLAG =  i_RI_LARGEREDEMPTIONFLAG,
            CR_RETURNCODE =  i_CR_RETURNCODE,
            CR_APPSHEETSERIALNO =  i_CR_APPSHEETSERIALNO,
            CR_TRANSACTIONCFMDATE =  i_CR_TRANSACTIONCFMDATE,
            CR_FUNDCODE =  i_CR_FUNDCODE,
            CR_BUSINESSCODE =  i_CR_BUSINESSCODE,
            CR_APPLICATIONVOL = TO_NUMBER(i_CR_APPLICATIONVOL),
            CR_TASERIALNO =  i_CR_TASERIALNO,
            CR_APPLICATIONAMOUNT =  i_CR_APPLICATIONAMOUNT,
            CR_TARGETFUNDCODE =  i_CR_TARGETFUNDCODE,
            CR_TAACCOUNTID =  i_CR_TAACCOUNTID,
            CR_ORIGINAPPLICATIONVOL =  i_CR_ORIGINAPPLICATIONVOL,
            CR_CONFIRMEDVOL = TO_NUMBER(i_CR_CONFIRMEDVOL),
            CR_CONFIRMEDAMOUNT = TO_NUMBER(i_CR_CONFIRMEDAMOUNT),
            CR_CHARGE = TO_NUMBER(i_CR_CHARGE),
            CR_NAV = TO_NUMBER(i_CR_NAV),
            CR_DEFDIVIDENDDMETHOD =  i_CR_DEFDIVIDENDDMETHOD,
            CR_RETURNMSG =  i_CR_RETURNMSG,
            CR_PAYCENTERID =  i_CR_PAYCENTERID,
            CR_CHANNELID =  i_CR_CHANNELID,
            CR_DEPOSITACCT =  i_CR_DEPOSITACCT,
            DATE_CREATE = TO_DATE(i_DATE_CREATE, 'yyyy-MM-dd'),
            DATE_MODIFY = TO_DATE(i_DATE_MODIFY, 'yyyy-MM-dd'),
            O_APPSHEETSERIALNO =  i_O_APPSHEETSERIALNO,
            RREMARK =  i_RREMARK
       WHERE REQ_ID=i_REQ_ID;
  EXCEPTION
    WHEN OTHERS THEN
        
         o_retCode := '-1';
         ROLLBACK;
      RETURN;
  END;
 /******************************************************************************
   --       PROC_TDY_LG_TDYHTRADERE_ADD
   -- 		增加数据
   -- 		输入参数：
   --			i_REQ_ID  i_本地生成的任务id
   --			i_PLATFORM_NUM  i_客户平台编号
   --			i_STATUS_CONFIRM  i_交易确认状态 0未确认 1已确认 2已成功撤单 3废单（若想知道是废单需调用客户交易记录接口，暂时无此动作）
   --			i_TYPE_TRADE  i_调用接口 01:PURCHASE-520003-手机基金认申购 02:CANCEL_ORDER-520006-用户交易撤单 03:REDEEM-520004-用户份额赎回
   --			i_STATUS_IO  i_0:支出交易 1:收入交易 2:取消交易
   --			i_CUST_NO  i_客户号
   --			i_TRANSACTIONACCOUNTID  i_交易账户
   --			i_TANO  i_TA代码
   --			i_BI_APPLICATIONAMT  i_申请金额(BI_...为购买接口入参)
   --			i_BI_MONEYACCOUNT  i_资金账户
   --			i_BI_CHANNELID  i_支付网点[110080]
   --			i_BI_BUYFLAG  i_强制购买标志，'0' 非强制购买，'1' 强制购买
   --			i_BI_TRANSACTORNAME  i_监护人姓名未成年人交易必填
   --			i_BI_TRANSACTORCERTTYPE  i_账户经办人证件类型 未成年人交易必填[110047]
   --			i_BI_TRANSACTORCERTNO  i_监护人证件号码未成年人交易必填
   --			i_BR_TRANSACTIONDATE  i_交易发生日期 格式为：YYYYMMDD
   --			i_BR_LIQDATE  i_购买结算日期 格式为：YYYYMMDD
   --			i_RI_APPLICATIONVOL  i_申请份数(RI_...为赎回接口返回入参)
   --			i_RI_LARGEREDEMPTIONFLAG  i_巨额赎回标志，0-放弃超额部分1-继续赎回，预约赎回、转换 
   --			i_CR_RETURNCODE  i_(CR_...为查询交易确认返回的数据)
   --			i_CR_APPSHEETSERIALNO  i_申请单编号
   --			i_CR_TRANSACTIONCFMDATE  i_crTransactioncfmdate
   --			i_CR_FUNDCODE  i_基金代码
   --			i_CR_BUSINESSCODE  i_业务类型[130010]
   --			i_CR_APPLICATIONVOL  i_申请基金份数 初始申报
   --			i_CR_TASERIALNO  i_TA 确认流水号
   --			i_CR_APPLICATIONAMOUNT  i_申请金额
   --			i_CR_TARGETFUNDCODE  i_目标基金代码
   --			i_CR_TAACCOUNTID  i_基金帐号
   --			i_CR_ORIGINAPPLICATIONVOL  i_原申请单编号 027 业务使用，表示转出时的申请单编号
   --			i_CR_CONFIRMEDVOL  i_确认份额
   --			i_CR_CONFIRMEDAMOUNT  i_确认金额
   --			i_CR_CHARGE  i_手续费
   --			i_CR_NAV  i_当日基金净值
   --			i_CR_DEFDIVIDENDDMETHOD  i_分红方式‘0’-红利转投‘1’-现金分红[110001]
   --			i_CR_RETURNMSG  i_交易处理返回代码系统处理后返回错误信息
   --			i_CR_PAYCENTERID  i_支付网点所属中心，查看数据字典[110079]
   --			i_CR_CHANNELID  i_支付渠道代码，查看数据字典[110080]
   --			i_CR_DEPOSITACCT  i_投资人银行卡号
   --			i_DATE_CREATE  i_记录创建日期
   --			i_DATE_MODIFY  i_记录最后修改日期
   --			i_O_APPSHEETSERIALNO  i_请求接口时返回的原始单号，备份对比用
   --			i_RREMARK  i_预留

   -- 		输出参数
   --   		o_retCode    返回标志位
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/

PROCEDURE PROC_TDY_LG_TDYHTRADERE_ADD(
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode     OUT VARCHAR2) IS

  extCount NUMBER;
  BEGIN
    o_retCode :=0;
	SELECT count(*)
	      INTO extCount
	      FROM TDYH_TRADE_RECORD a
	     WHERE a.REQ_ID = i_REQ_ID;
    IF(i_TYPE_TRADE = '02')THEN --撤单
    	IF extCount = 0 THEN --无单可撤 逻辑有误
	      o_retCode := 1;
	      RETURN;
	    ELSE
	    	update TDYH_TRADE_RECORD set STATUS_CONFIRM = '2',STATUS_IO='2',CR_APPSHEETSERIALNO=i_O_APPSHEETSERIALNO,DATE_MODIFY=sysdate;
	    END IF;
    ELSE -- 购买、赎回
	
	    IF extCount != 0 THEN 
	      o_retCode := -1;
	      RETURN;
	    END IF;
	
	    INSERT INTO TDYH_TRADE_RECORD(
							REQ_ID,
							PLATFORM_NUM,
							STATUS_CONFIRM,
							TYPE_TRADE,
							STATUS_IO,
							CUST_NO,
							TRANSACTIONACCOUNTID,
							TANO,
							BI_APPLICATIONAMT,
							BI_MONEYACCOUNT,
							BI_CHANNELID,
							BI_BUYFLAG,
							BI_TRANSACTORNAME,
							BI_TRANSACTORCERTTYPE,
							BI_TRANSACTORCERTNO,
							BR_TRANSACTIONDATE,
							BR_LIQDATE,
							RI_APPLICATIONVOL,
							RI_LARGEREDEMPTIONFLAG,
							CR_RETURNCODE,
							CR_APPSHEETSERIALNO,
							CR_TRANSACTIONCFMDATE,
							CR_FUNDCODE,
							CR_BUSINESSCODE,
							CR_APPLICATIONVOL,
							CR_TASERIALNO,
							CR_APPLICATIONAMOUNT,
							CR_TARGETFUNDCODE,
							CR_TAACCOUNTID,
							CR_ORIGINAPPLICATIONVOL,
							CR_CONFIRMEDVOL,
							CR_CONFIRMEDAMOUNT,
							CR_CHARGE,
							CR_NAV,
							CR_DEFDIVIDENDDMETHOD,
							CR_RETURNMSG,
							CR_PAYCENTERID,
							CR_CHANNELID,
							CR_DEPOSITACCT,
							DATE_CREATE,
							O_APPSHEETSERIALNO,
							RREMARK
					)VALUES (
	           i_REQ_ID,
	           i_PLATFORM_NUM,
	           i_STATUS_CONFIRM,
	           i_TYPE_TRADE,
	           i_STATUS_IO,
	           i_CUST_NO,
	           i_TRANSACTIONACCOUNTID,
	           i_TANO,
	           TO_NUMBER(i_BI_APPLICATIONAMT),
	           i_BI_MONEYACCOUNT,
	           i_BI_CHANNELID,
	           i_BI_BUYFLAG,
	           i_BI_TRANSACTORNAME,
	           i_BI_TRANSACTORCERTTYPE,
	           i_BI_TRANSACTORCERTNO,
	           i_BR_TRANSACTIONDATE,
	           i_BR_LIQDATE,
	           TO_NUMBER(i_RI_APPLICATIONVOL),
	           i_RI_LARGEREDEMPTIONFLAG,
	           i_CR_RETURNCODE,
	           i_CR_APPSHEETSERIALNO,
	           i_CR_TRANSACTIONCFMDATE,
	           i_CR_FUNDCODE,
	           i_CR_BUSINESSCODE,
	           TO_NUMBER(i_CR_APPLICATIONVOL),
	           i_CR_TASERIALNO,
	           i_CR_APPLICATIONAMOUNT,
	           i_CR_TARGETFUNDCODE,
	           i_CR_TAACCOUNTID,
	           i_CR_ORIGINAPPLICATIONVOL,
	           TO_NUMBER(i_CR_CONFIRMEDVOL),
	           TO_NUMBER(i_CR_CONFIRMEDAMOUNT),
	           TO_NUMBER(i_CR_CHARGE),
	           TO_NUMBER(i_CR_NAV),
	           i_CR_DEFDIVIDENDDMETHOD,
	           i_CR_RETURNMSG,
	           i_CR_PAYCENTERID,
	           i_CR_CHANNELID,
	           i_CR_DEPOSITACCT,
	           sysdate,
	           i_O_APPSHEETSERIALNO,
	           i_RREMARK
						);
    END IF;
    

  EXCEPTION
    WHEN OTHERS THEN
      o_retCode := -2;
      RETURN;
  END;
/******************************************************************************
   --       PROC_TDY_LG_TDYHTRADERE_DEL
   -- 		增加数据
   -- 		输入参数：
   --           REQ_ID
   -- 		输出参数
   --   		o_retCode    返回标志位
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/
PROCEDURE PROC_TDY_LG_TDYHTRADERE_DEL(
                i_REQ_ID   IN  VARCHAR2,
                o_retCode     OUT VARCHAR2) IS
  BEGIN
    o_retCode :=0;

    DELETE TDYH_TRADE_RECORD WHERE REQ_ID = i_REQ_ID;
  EXCEPTION
    WHEN OTHERS THEN
      o_retCode := -1;
      RETURN;
  END;
  --查询需要确认的数据列表
PROCEDURE PROC_TDY_LG_SYNCLI(
                o_retCode     OUT VARCHAR2,
                o_trade_list OUT ref_trade_li) IS

  --extCount NUMBER;
  BEGIN
    o_retCode :=0;
    OPEN o_trade_list FOR
    select t.cust_no,to_char(min(t.date_create),'yyyymmdd') as begindate,to_char(sysdate,'yyyymmdd') as enddate from TDYH_TRADE_RECORD t 
	where t.STATUS_CONFIRM='0' group by t.cust_no;
	RETURN;
  EXCEPTION
   WHEN OTHERS THEN
    IF o_trade_list%ISOPEN THEN
        CLOSE o_trade_list;
      END IF;
      o_retCode := -1;
      RETURN;
  END;
/******************************************************************************
   --       PROC_TDY_LG_SYNCTRADE_U
   -- 		同步交易数据
   -- 		输入参数：
   --	i_CR_RETURNCODE  i_(CR_...为查询交易确认返回的数据)
   --	i_CR_APPSHEETSERIALNO  i_申请单编号
   --	i_CR_TRANSACTIONCFMDATE  i_crTransactioncfmdate
   --	i_CR_FUNDCODE  i_基金代码
   --	i_CR_BUSINESSCODE  i_业务类型[130010]
   --	i_CR_APPLICATIONVOL  i_申请基金份数 初始申报
   --	i_CR_TASERIALNO  i_TA 确认流水号
   --	i_CR_APPLICATIONAMOUNT  i_申请金额
   --	i_CR_TARGETFUNDCODE  i_目标基金代码
   --	i_CR_TAACCOUNTID  i_基金帐号
   --	i_CR_ORIGINAPPLICATIONVOL  i_原申请单编号 027 业务使用，表示转出时的申请单编号
   --	i_CR_CONFIRMEDVOL  i_确认份额
   --	i_CR_CONFIRMEDAMOUNT  i_确认金额
   --	i_CR_CHARGE  i_手续费
   --	i_CR_NAV  i_当日基金净值
   --	i_CR_DEFDIVIDENDDMETHOD  i_分红方式‘0’-红利转投‘1’-现金分红[110001]
   --	i_CR_RETURNMSG  i_交易处理返回代码系统处理后返回错误信息
   --	i_CR_PAYCENTERID  i_支付网点所属中心，查看数据字典[110079]
   --	i_CR_CHANNELID  i_支付渠道代码，查看数据字典[110080]
   --	i_CR_DEPOSITACCT  i_投资人银行卡号

   -- 		输出参数
   --   		o_retCode    返回标志位
   -- REVISIONS:
   --    Ver           Date            Author                 Description
   -- ---------      ----------      ----------        --------------------------
   --   1.0         2016-05-27     lenovo              create this procedure.
  ******************************************************************************/
PROCEDURE PROC_TDY_LG_SYNCTRADE_U(
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
                o_retCode OUT VARCHAR2) IS
     --extCount NUMBER;
BEGIN
   o_retCode:='0';
       UPDATE TDYH_TRADE_RECORD
       SET
            CR_RETURNCODE =  i_CR_RETURNCODE,
            CR_APPSHEETSERIALNO =  i_CR_APPSHEETSERIALNO,
            CR_TRANSACTIONCFMDATE =  i_CR_TRANSACTIONCFMDATE,
            CR_FUNDCODE =  i_CR_FUNDCODE,
            CR_BUSINESSCODE =  i_CR_BUSINESSCODE,
            CR_APPLICATIONVOL = TO_NUMBER(i_CR_APPLICATIONVOL),
            CR_TASERIALNO =  i_CR_TASERIALNO,
            CR_APPLICATIONAMOUNT =  i_CR_APPLICATIONAMOUNT,
            CR_TARGETFUNDCODE =  i_CR_TARGETFUNDCODE,
            CR_TAACCOUNTID =  i_CR_TAACCOUNTID,
            CR_ORIGINAPPLICATIONVOL =  i_CR_ORIGINAPPLICATIONVOL,
            CR_CONFIRMEDVOL = TO_NUMBER(i_CR_CONFIRMEDVOL),
            CR_CONFIRMEDAMOUNT = TO_NUMBER(i_CR_CONFIRMEDAMOUNT),
            CR_CHARGE = TO_NUMBER(i_CR_CHARGE),
            CR_NAV = TO_NUMBER(i_CR_NAV),
            CR_DEFDIVIDENDDMETHOD =  i_CR_DEFDIVIDENDDMETHOD,
            CR_RETURNMSG =  i_CR_RETURNMSG,
            CR_PAYCENTERID =  i_CR_PAYCENTERID,
            CR_CHANNELID =  i_CR_CHANNELID,
            CR_DEPOSITACCT =  i_CR_DEPOSITACCT,
            DATE_MODIFY = sysdate,
            STATUS_CONFIRM='1'
       WHERE O_APPSHEETSERIALNO=i_CR_APPSHEETSERIALNO;
  EXCEPTION
    WHEN OTHERS THEN
        
         o_retCode := '-1';
         ROLLBACK;
      RETURN;
  END;
  --新查询逻辑
  PROCEDURE PROC_TDY_LG_TDYHTRADERE_QUERY(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                totalNum OUT VARCHAR2,
                o_item_list OUT REF_SETCUR) IS
				
	sql_where varchar2(1000);--注意：按条件搜索时DATE_CREATE与DATE_MODIFY分别表示需查询的开始和结束日期
	sql_count varchar2(2000);
	sql_list varchar2(3000);
	
	v_totalnum REF_SETCUR;--存放数据临时游标
	
	v_pos Number := 1;--用来记录v_result每行开始字符的位置
BEGIN
   o_retCode:=0;
   sql_where := sql_where || ' where 1=1';
   IF i_REQ_ID IS NOT NULL THEN --主键id
			sql_where := sql_where || ' AND a.REQ_ID = ''' || i_REQ_ID ||'''';
   END IF;
   IF i_PLATFORM_NUM IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.PLATFORM_NUM = ''' || i_PLATFORM_NUM ||'''';
   END IF;
   IF i_STATUS_CONFIRM IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.STATUS_CONFIRM = ''' || i_STATUS_CONFIRM ||'''';
   END IF;
   IF i_TYPE_TRADE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.TYPE_TRADE = ''' || i_TYPE_TRADE ||'''';
   END IF;
   IF i_STATUS_IO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.STATUS_IO = ''' || i_STATUS_IO ||'''';
   END IF;
   IF i_CUST_NO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CUST_NO = ''' || i_CUST_NO ||'''';
   END IF;
   IF i_TANO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.TANO = ''' || i_TANO ||'''';
   END IF;
   IF i_BI_CHANNELID IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.BI_CHANNELID = ''' || i_BI_CHANNELID ||'''';
   END IF;
   IF i_CR_FUNDCODE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CR_FUNDCODE = ''' || i_CR_FUNDCODE ||'''';
   END IF;
   IF i_CR_BUSINESSCODE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CR_BUSINESSCODE = ''' || i_CR_BUSINESSCODE ||'''';
   END IF;
   IF i_DATE_CREATE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.DATE_CREATE >= ''' || TO_DATE(i_DATE_CREATE, 'yyyy-MM-dd') ||'''';
   END IF;
   IF i_DATE_MODIFY IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.DATE_CREATE <= ''' || TO_DATE(i_DATE_MODIFY, 'yyyy-MM-dd') ||'''';
   END IF;
   
	sql_count := 'select count(*) from TDYH_TRADE_RECORD a'||sql_where;--查询总数

	sql_list := '
   SELECT 
		REQ_ID,
		PLATFORM_NUM,
		STATUS_CONFIRM,
		TYPE_TRADE,
		STATUS_IO,
		CUST_NO,
		TRANSACTIONACCOUNTID,
		TANO,
		to_char(BI_APPLICATIONAMT,''999999999999999.99''),
		BI_MONEYACCOUNT,
		BI_CHANNELID,
		BI_BUYFLAG,
		BI_TRANSACTORNAME,
		BI_TRANSACTORCERTTYPE,
		BI_TRANSACTORCERTNO,
		BR_TRANSACTIONDATE,
		BR_LIQDATE,
		RI_APPLICATIONVOL,
		RI_LARGEREDEMPTIONFLAG,
		CR_RETURNCODE,
		CR_APPSHEETSERIALNO,
		CR_TRANSACTIONCFMDATE,
		CR_FUNDCODE,
		CR_BUSINESSCODE,
		CR_APPLICATIONVOL,
		CR_TASERIALNO,
		CR_APPLICATIONAMOUNT,
		CR_TARGETFUNDCODE,
		CR_TAACCOUNTID,
		CR_ORIGINAPPLICATIONVOL,
		to_char(CR_CONFIRMEDVOL,''999999999999999.99''),
		to_char(CR_CONFIRMEDAMOUNT,''999999999999999.99''),
		to_char(trunc(CR_CHARGE,2),''999999999999999.99''),
		CR_NAV,
		CR_DEFDIVIDENDDMETHOD,
		CR_RETURNMSG,
		CR_PAYCENTERID,
		CR_CHANNELID,
		CR_DEPOSITACCT,
		DATE_CREATE,
		DATE_MODIFY,
		O_APPSHEETSERIALNO,
		RREMARK
   FROM(SELECT 
		REQ_ID,
		PLATFORM_NUM,
		STATUS_CONFIRM,
		TYPE_TRADE,
		STATUS_IO,
		CUST_NO,
		TRANSACTIONACCOUNTID,
		TANO,
		BI_APPLICATIONAMT,
		BI_MONEYACCOUNT,
		BI_CHANNELID,
		BI_BUYFLAG,
		BI_TRANSACTORNAME,
		BI_TRANSACTORCERTTYPE,
		BI_TRANSACTORCERTNO,
		BR_TRANSACTIONDATE,
		BR_LIQDATE,
		RI_APPLICATIONVOL,
		RI_LARGEREDEMPTIONFLAG,
		CR_RETURNCODE,
		CR_APPSHEETSERIALNO,
		CR_TRANSACTIONCFMDATE,
		CR_FUNDCODE,
		CR_BUSINESSCODE,
		CR_APPLICATIONVOL,
		CR_TASERIALNO,
		CR_APPLICATIONAMOUNT,
		CR_TARGETFUNDCODE,
		CR_TAACCOUNTID,
		CR_ORIGINAPPLICATIONVOL,
		CR_CONFIRMEDVOL,
		CR_CONFIRMEDAMOUNT,
		CR_CHARGE,
		CR_NAV,
		CR_DEFDIVIDENDDMETHOD,
		CR_RETURNMSG,
		CR_PAYCENTERID,
		CR_CHANNELID,
		CR_DEPOSITACCT,
		DATE_CREATE,
		DATE_MODIFY,
		O_APPSHEETSERIALNO,
		RREMARK,
	ROWNUM  ROW_ID
	FROM TDYH_TRADE_RECORD a '|| sql_where ||
	')WHERE ROW_ID >='|| to_number(begNum)||' AND ROW_ID < '|| (to_number(begNum) + to_number(fetchNum));
	--dbms_output.put_line(sql_list);--打印测试
	/**
	WHILE v_pos<= LENGTH(sql_list) LOOP --oracle最多只能显示256个 因此要用循环读取的方法显示long value
        DBMS_OUTPUT.PUT_LINE(SUBSTR(sql_list, v_pos, 200));
        v_pos:= v_pos+ 200;
 	END LOOP;
	*/
	OPEN v_totalnum FOR sql_count;
    FETCH v_totalnum into totalNum;
	
	OPEN o_item_list FOR sql_list;
	
    RETURN;
     EXCEPTION
    WHEN OTHERS THEN
		IF v_totalnum%ISOPEN THEN
        CLOSE v_totalnum;
      END IF;
	  
      IF o_item_list%ISOPEN THEN
        CLOSE o_item_list;
      END IF;
      
      o_retCode := -1;
      RETURN;
  END;
  --统计信息
  PROCEDURE PROC_TDY_LG_STATISTICS(
                begNum   IN VARCHAR2,
                fetchNum IN VARCHAR2,
				i_REQ_ID IN VARCHAR2,
				i_PLATFORM_NUM IN VARCHAR2,
				i_STATUS_CONFIRM IN VARCHAR2,
				i_TYPE_TRADE IN VARCHAR2,
				i_STATUS_IO IN VARCHAR2,
				i_CUST_NO IN VARCHAR2,
				i_TRANSACTIONACCOUNTID IN VARCHAR2,
				i_TANO IN VARCHAR2,
				i_BI_APPLICATIONAMT IN VARCHAR2,
				i_BI_MONEYACCOUNT IN VARCHAR2,
				i_BI_CHANNELID IN VARCHAR2,
				i_BI_BUYFLAG IN VARCHAR2,
				i_BI_TRANSACTORNAME IN VARCHAR2,
				i_BI_TRANSACTORCERTTYPE IN VARCHAR2,
				i_BI_TRANSACTORCERTNO IN VARCHAR2,
				i_BR_TRANSACTIONDATE IN VARCHAR2,
				i_BR_LIQDATE IN VARCHAR2,
				i_RI_APPLICATIONVOL IN VARCHAR2,
				i_RI_LARGEREDEMPTIONFLAG IN VARCHAR2,
				i_CR_RETURNCODE IN VARCHAR2,
				i_CR_APPSHEETSERIALNO IN VARCHAR2,
				i_CR_TRANSACTIONCFMDATE IN VARCHAR2,
				i_CR_FUNDCODE IN VARCHAR2,
				i_CR_BUSINESSCODE IN VARCHAR2,
				i_CR_APPLICATIONVOL IN VARCHAR2,
				i_CR_TASERIALNO IN VARCHAR2,
				i_CR_APPLICATIONAMOUNT IN VARCHAR2,
				i_CR_TARGETFUNDCODE IN VARCHAR2,
				i_CR_TAACCOUNTID IN VARCHAR2,
				i_CR_ORIGINAPPLICATIONVOL IN VARCHAR2,
				i_CR_CONFIRMEDVOL IN VARCHAR2,
				i_CR_CONFIRMEDAMOUNT IN VARCHAR2,
				i_CR_CHARGE IN VARCHAR2,
				i_CR_NAV IN VARCHAR2,
				i_CR_DEFDIVIDENDDMETHOD IN VARCHAR2,
				i_CR_RETURNMSG IN VARCHAR2,
				i_CR_PAYCENTERID IN VARCHAR2,
				i_CR_CHANNELID IN VARCHAR2,
				i_CR_DEPOSITACCT IN VARCHAR2,
				i_DATE_CREATE IN VARCHAR2,
				i_DATE_MODIFY IN VARCHAR2,
				i_O_APPSHEETSERIALNO IN VARCHAR2,
				i_RREMARK IN VARCHAR2,
                o_retCode OUT VARCHAR2,
                --totalNum OUT VARCHAR2,
                o_item_list OUT REF_SETCUR) IS
				
	sql_where varchar2(1000);--注意：按条件搜索时DATE_CREATE与DATE_MODIFY分别表示需查询的开始和结束日期
	--sql_count varchar2(2000);
	sql_list varchar2(3000);
	
	--v_totalnum REF_SETCUR;--存放数据临时游标
	
	v_pos Number := 1;--用来记录v_result每行开始字符的位置
BEGIN
   o_retCode:=0;
   sql_where := sql_where || ' where 1=1';
   IF i_REQ_ID IS NOT NULL THEN --主键id
			sql_where := sql_where || ' AND a.REQ_ID = ''' || i_REQ_ID ||'''';
   END IF;
   IF i_PLATFORM_NUM IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.PLATFORM_NUM = ''' || i_PLATFORM_NUM ||'''';
   END IF;
   IF i_STATUS_CONFIRM IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.STATUS_CONFIRM = ''' || i_STATUS_CONFIRM ||'''';
   END IF;
   IF i_TYPE_TRADE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.TYPE_TRADE = ''' || i_TYPE_TRADE ||'''';
   END IF;
   IF i_STATUS_IO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.STATUS_IO = ''' || i_STATUS_IO ||'''';
   END IF;
   IF i_CUST_NO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CUST_NO = ''' || i_CUST_NO ||'''';
   END IF;
   IF i_TANO IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.TANO = ''' || i_TANO ||'''';
   END IF;
   IF i_BI_CHANNELID IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.BI_CHANNELID = ''' || i_BI_CHANNELID ||'''';
   END IF;
   IF i_CR_FUNDCODE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CR_FUNDCODE = ''' || i_CR_FUNDCODE ||'''';
   END IF;
   IF i_CR_BUSINESSCODE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.CR_BUSINESSCODE = ''' || i_CR_BUSINESSCODE ||'''';
   END IF;
   IF i_DATE_CREATE IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.DATE_CREATE >= ''' || TO_DATE(i_DATE_CREATE, 'yyyy-MM-dd') ||'''';
   END IF;
   IF i_DATE_MODIFY IS NOT NULL THEN 
			sql_where := sql_where || ' AND a.DATE_CREATE <= ''' || TO_DATE(i_DATE_MODIFY, 'yyyy-MM-dd') ||'''';
   END IF;
   
	--sql_count := 'select count(*) from TDYH_TRADE_RECORD a'||sql_where;--查询总数

	sql_list := '
		select 
		to_char(AVG(q.BI_APPLICATIONAMT),''999999999999999.99'') AVGBIAPPLICATIONAMT,
		to_char(AVG(q.CR_CONFIRMEDVOL),''999999999999999.99'') AVGCRCONFIRMEDVOL,
		to_char(AVG(q.CR_CONFIRMEDAMOUNT),''999999999999999.99'') AVGCRCONFIRMEDAMOUNT,
		to_char(AVG(q.CR_CHARGE),''999999999999999.99'') AVGCRCHARGE,
		to_char(SUM(q.BI_APPLICATIONAMT),''999999999999999.99'') SUMBIAPPLICATIONAMT,
		to_char(SUM(q.CR_CONFIRMEDVOL),''999999999999999.99'') SUMCRCONFIRMEDVOL,
		to_char(SUM(q.CR_CONFIRMEDAMOUNT),''999999999999999.99'') SUMCRCONFIRMEDAMOUNT,
		to_char(SUM(q.CR_CHARGE),''999999999999999.99'') SUMCRCHARGE
		from(
		select a.*, 1 as b from TDYH_TRADE_RECORD a'||sql_where||
		') q group by b';
	--dbms_output.put_line(sql_list);--打印测试
	/**
	WHILE v_pos<= LENGTH(sql_list) LOOP --oracle最多只能显示256个 因此要用循环读取的方法显示long value
        DBMS_OUTPUT.PUT_LINE(SUBSTR(sql_list, v_pos, 200));
        v_pos:= v_pos+ 200;
 	END LOOP;
	*/
	/**
	OPEN v_totalnum FOR sql_count;
    FETCH v_totalnum into totalNum;
	*/
	OPEN o_item_list FOR sql_list;
	
    RETURN;
     EXCEPTION
    WHEN OTHERS THEN
    /**
		IF v_totalnum%ISOPEN THEN
        CLOSE v_totalnum;
      END IF;
	  */
      IF o_item_list%ISOPEN THEN
        CLOSE o_item_list;
      END IF;
      
      o_retCode := -1;
      RETURN;
  END;
  
  
END;
/
